### ISSUE TITLE
4.0 - crash with Algotech's demo

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/virtualc64#638]
When trying to insert the .d64 of the VF-SSDPCM1 Super Plus by Algotech , the emulator goes crash.
Same file works correctly on version 3.4 and earlier

https://csdb.dk/release/?id=163621

[vf-ssdpcm1superplus.d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/5937910/vf-ssdpcm1superplus.d64.zip)

**Comment by dirkwhoffmann** [comment]
Nice catch. The error happens before calling this function: 

```C++
bool
FSDevice::importVolume(const u8 *src, usize size, ErrorCode *err)
{
    assert(src != nullptr);

    debug(FS_DEBUG, "Importing file system (%zu bytes)...\n", size);

    // Only proceed if the buffer size matches
    if (blocks.size() * 256 != size) {
        warn("BUFFER SIZE MISMATCH (%lu %lu)\n", blocks.size(), blocks.size() * 256);
        ...
```

Apparently, v4.0 doesn't handle large D64 files any more. Background: D64 files come in six different sizes:

```C++
    static const usize D64_683_SECTORS     = 174848;
    static const usize D64_683_SECTORS_ECC = 175531;
    static const usize D64_768_SECTORS     = 196608;
    static const usize D64_768_SECTORS_ECC = 197376;
    static const usize D64_802_SECTORS     = 205312;
    static const usize D64_802_SECTORS_ECC = 206114;
```

The given file contains extra sectors which screws up the internal buffers:
```
hoff  staff  196608 26 Jan  2020 /Users/hoff/Downloads/vf-ssdpcm1superplus.d64
```

**Comment by dirkwhoffmann** [comment]
Fixed in v4.0.1. Thanks for reporting!

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/108602161-d75ba080-73a0-11eb-875f-dc26bfd0e5f7.png)

I guess the web version still shows this error 🤔...  right? I will have to merge the fix too right?

**Comment by dirkwhoffmann** [comment]
Yes, but it's only one file to merge.

**Comment by mithrendal** [comment]
Merged all latest changes in v4.0.1 into the the web version 👍🏻 . No crashing anymore.
