### ISSUE TITLE
Crash during shutdown

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#798]
To my shame, I haven't managed to implement a safe shutdown procedure for years.  It still crashes from time to time on exit (e.g., today):

<img width="1112" alt="Bildschirmfoto 2024-06-14 um 19 09 41" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/a7eac1b0-1d9b-48c7-94fa-3a3c92c03f01">

**Comment by dirkwhoffmann** [comment]
Hopefully fixed in v5.0b5

I've added a locking mechanism to the audio unit. My suspicion is that the audio unit callbacks are still invoked after the audio unit has been shut down.

**Comment by mithrendal** [comment]
I finally figured out how to reproduce the shutdown bug, it is still present in v5.0.beta6

how to reproduce

1. open virtualc64
2. goto preferences and set `runahead` to a value greater than 0
3. click on the red button to close the window
4. a dialog pops up "do you want to keep this new document "Untitled"?
5. choose `delete` 
6. windows closes and macos crashreport opens


it only crashes with `runahead enabled` (i.e. > 0), when `runahead is disabled` (i.e. ==0)  shutdown procedure behaves normal 😎.

**Comment by dirkwhoffmann** [comment]
Confirmed! Thanks for making the bug reproducible!

<img width="621" alt="Bildschirmfoto 2024-06-26 um 21 24 27" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/1615ae57-4409-4249-aa54-ba7e4f92dced">

I'm already on his trail... stay tuned...

**Comment by dirkwhoffmann** [comment]
Here is what's happening: Class `Keyboard` has an overloaded `=` operator:

```C++
Keyboard& operator= (const Keyboard& other) {

        CLONE_ARRAY(kbMatrixRow)
        CLONE_ARRAY(kbMatrixCol)
        CLONE_ARRAY(kbMatrixRowCnt)
        CLONE_ARRAY(kbMatrixColCnt)
        CLONE(shiftLock)
        CLONE(pending)
        
        return *this;
    }
```

Variable `pending` is a `RingBuffer`which has the following members:

```C++
template <class T, isize capacity> struct RingBuffer
{
    // Element storage
    T *elements = new T[capacity]();

    // Read and write pointers
    isize r, w;

    ...
```

The bug is that `RingBuffer` does not overload the `=` operator itself. The default implementation copies all members over which means that `elements` points to the same memory area after the assignment. When run-ahead is active, we end up with two emulator instances sharing the same `elements` array. The app crashes with a malloc double-free error when destructing the second instance during shutdown.

The fix is to provide a custom `=` operator like this:

```C++
RingBuffer& operator= (const RingBuffer& other) {

        memcpy(elements, other.elements, capacity);
        r = other.r;
        w = other.w;

        return *this;
    }
```

**Comment by mithrendal** [comment]
very beautiful !

**Comment by dirkwhoffmann** [comment]
Fixed in v5.0b7
